### ISSUE TITLE
Meme, Cat, Dog commands don't work if media is a video

### ISSUE THREAD

**Issue by LeoCatsune** [MenuDocs/Discord.js-v12-Tutorials#11]
## The Problem
Discord image embeds don't work with videos, however the imgur data sometimes results in a video being passed to the embed constructor.

## The Solution
MIME Type filtering could be implemented, using the `mimetype` field from hot.json.

**Comment by NullPointDev** [comment]
#12

**Comment by Strandxo** [comment]
Thank you!
