### ISSUE TITLE
Problem on servinfo and userinfo

### ISSUE THREAD

**Issue by iDrunK65** [MenuDocs/Discord.js-v12-Tutorials#4]
For those commands, this line not working
`**❯ Roles [${roles.length}]:** ${roles.length < 10 ? roles.join(', ') : roles.length > 10 ? this.client.utils.trimArray(roles) : 'None'}`,`

And i get this error : (node:13604) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'utils' of undefined

**Comment by JonasSchiott** [comment]
Add `this.client = bla` to your command class (it’s shown in a previous video)

**Comment by Strandxo** [comment]
In future use our discord to ask for support with your code.
