### ISSUE TITLE
Unhandled Promises Rejection issue

### ISSUE THREAD

**Issue by SYOTOSGrag** [MenuDocs/Discord.js-v12-Tutorials#9]
The error is `UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict'`
The error has to do with episode 2 about the command handler.

**Comment by Strandxo** [comment]
Please join our discord for further assistance with this issue. Thanks! https://discord.gg/MenuDocs
